const fs = require('fs');
const path = require('path');
const XLSX = require('xlsx');

const ROOT = path.resolve(__dirname, '..');
const READY = path.join(ROOT, 'output', 'import-ready');
const REPORTS = path.join(ROOT, 'output', 'reports');
const RUNTIME = path.join(ROOT, 'runtime', 'imports');
const modules = JSON.parse(fs.readFileSync(path.join(ROOT, 'config', 'modules.json'), 'utf8')).modules;

function boolEnv(name, fallback = true) {
  const value = process.env[name];
  if (value == null || value === '') return fallback;
  return String(value).toLowerCase() === 'true';
}

function countCsvRows(filePath) {
  const wb = XLSX.readFile(filePath, { raw: false });
  const sheet = wb.Sheets[wb.SheetNames[0]];
  return XLSX.utils.sheet_to_json(sheet, { defval: '', raw: false }).length;
}

function clearRuntime() {
  fs.mkdirSync(RUNTIME, { recursive: true });
  for (const entry of fs.readdirSync(RUNTIME)) {
    if (!entry.startsWith('.')) fs.rmSync(path.join(RUNTIME, entry), { recursive: true, force: true });
  }
}

const reportPath = path.join(REPORTS, 'latest-preparation.json');
if (!fs.existsSync(reportPath)) throw new Error('DPE report is missing: output/reports/latest-preparation.json');
const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));

if (boolEnv('DPE_REQUIRE_ZERO_REJECTIONS', true) && Number(report.totals?.rejected || 0) !== 0) {
  throw new Error(`DPE validation failed: ${report.totals.rejected} row(s) remain rejected.`);
}
if (boolEnv('DPE_REQUIRE_CLASSIFIED', true) && Array.isArray(report.unclassified) && report.unclassified.length) {
  throw new Error(`DPE validation failed: ${report.unclassified.length} dataset(s) remain unclassified.`);
}
if (!['READY', 'READY_WITH_REVIEW'].includes(report.status)) {
  throw new Error(`DPE validation failed with status ${report.status || 'UNKNOWN'}.`);
}

clearRuntime();
const manifest = {
  runId: report.runId,
  generatedAt: new Date().toISOString(),
  dpeStatus: report.status,
  dpeTotals: report.totals,
  files: [],
  noDataModules: []
};

for (const module of modules) {
  const source = path.join(READY, module.output);
  if (!fs.existsSync(source)) {
    manifest.noDataModules.push(module.id);
    continue;
  }
  const destination = path.join(RUNTIME, module.output);
  fs.copyFileSync(source, destination);
  manifest.files.push({
    module: module.id,
    file: module.output,
    rows: countCsvRows(destination),
    runtimePath: path.relative(ROOT, destination)
  });
}

if (!manifest.files.length) throw new Error('No import-ready module CSV files were generated by the DPE.');
fs.writeFileSync(path.join(RUNTIME, 'manifest.json'), JSON.stringify(manifest, null, 2));
console.log(`Validated and staged ${manifest.files.length} module file(s) for ADSE import.`);
for (const item of manifest.files) console.log(`- ${item.module}: ${item.rows} row(s) -> ${item.file}`);
